[ffistan]
git-tree-sha1 = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
lazy = true

    [[ffistan.download]]
    sha256 = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
    url = "https://github.com/WardBrian/ffistan/releases/download/v0.1.0/ffistan-0.1.0.tar.gz"
