[tinystan]
git-tree-sha1 = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
lazy = true

[[tinystan.download]]
sha256 = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
url = "https://github.com/WardBrian/tinystan/releases/download/v0.1.0/tinystan-0.1.0.tar.gz"
