name = "FFIStan"
uuid = "3a8caf9d-1ca3-4bd7-a835-128840ab73a4"
authors = ["Brian Ward <bward@flatironinstitute.org>"]
version = "0.1.0"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
julia = "1.6"
LazyArtifacts = "1"
